### ISSUE TITLE
Clarification on random generation

### ISSUE THREAD

**Issue by stuhealthcaregateway** [geditdk/text-file-generator#1]
Hi,

Can you clarify the line
xxxxx must be randomly generated with one of the following values:

Does this mean I need to create a completely random string, or select one of the list of values, randomly?

Cheers,

**Comment by geditdk** [comment]
Hi @stuhealthcaregateway,

It means to select one from the list of values:

```
A12345
B98765
C11111
D99999
E15975
```

So, `A12345 ` or `1B98765` or `C11111`, etc

I hope this answers your question.

Thanks,
Dave
